---
version: '3.7'
services:
  php-fpm:
    image: memoryleak/php:7.1-fpm
    volumes:
      - ./var/www/:/var/www/

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./var/www/:/var/www/
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  percona:
    image: percona:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal


  redis:
    image: redis:alpine
